"""
CodeGen produces standalone, human-readable Julia scripts for BeamletOptics.jl
representing the imported Zemax optical system.
"""

using Printf

"""
    fmt_len(val_m::Real)::String

Formats a length value in meters into standard optical millimetre notation with `mm` suffix.
"""
function fmt_len(val_m::Real)::String
    if isinf(val_m)
        return "Inf"
    elseif iszero(val_m)
        return "0.0mm"
    else
        val_mm = val_m * 1e3
        return @sprintf("%.4gmm", val_mm)
    end
end

"""
    generate_bmo_code(zmx_sys::ZmxSystem, elements::Vector{ZmxElement})::String

Generates clean Julia source code defining the optical system.
"""
function generate_bmo_code(zmx_sys::ZmxSystem, elements::Vector{ZmxElement})::String
    buf = IOBuffer()
    
    primary_wvl = zmx_sys.wavelengths[zmx_sys.primary_wavelength_idx]

    println(buf, "# ==============================================================================")
    println(buf, "# Optical System: $(isempty(zmx_sys.title) ? "Zemax Import" : zmx_sys.title)")
    println(buf, "# Generated by BeamletOpticsZMX.jl")
    println(buf, "# ==============================================================================")
    println(buf, "")
    println(buf, "using BeamletOptics")
    println(buf, "using LinearAlgebra")
    println(buf, "")
    println(buf, "const mm = 1e-3")
    println(buf, "")
    println(buf, "# --- Optical Components ---")
    
    obj_names = String[]
    det_name = ""
    elem_counter = 1

    for el in elements
        if isa(el, ZmxSinglet)
            var_name = "lens_$elem_counter"
            push!(obj_names, var_name)
            
            is_asph = el.front_surface.surface_type == :EVENASPH || el.back_surface.surface_type == :EVENASPH
            r1_str = fmt_len(el.front_surface.radius)
            r2_str = fmt_len(el.back_surface.radius)
            ct_str = fmt_len(el.center_thickness)
            d_str = fmt_len(el.diameter)
            y_str = fmt_len(el.axial_position)
            
            n_func = resolve_refractive_index(el.glass_name, el.nd, el.vd)
            n_val = round(n_func(primary_wvl), digits=5)

            println(buf, "# $(el.name) (Glass: $(el.glass_name), n ≈ $n_val)")
            if !is_asph
                println(buf, "$var_name = SphericalLens($r1_str, $r2_str, $ct_str, $d_str, λ -> $n_val)")
            else
                println(buf, "s_front_$elem_counter = EvenAsphericalSurface($r1_str, $d_str, $(el.front_surface.conic), $(el.front_surface.parms))")
                println(buf, "s_back_$elem_counter = EvenAsphericalSurface($r2_str, $d_str, $(el.back_surface.conic), $(el.back_surface.parms))")
                println(buf, "$var_name = Lens(s_front_$elem_counter, s_back_$elem_counter, $ct_str, λ -> $n_val)")
            end
            println(buf, "translate3d!($var_name, [0.0, $y_str, 0.0])")
            println(buf, "")
            elem_counter += 1

        elseif isa(el, ZmxDoublet)
            var_name = "doublet_$elem_counter"
            push!(obj_names, var_name)
            
            r1_str = fmt_len(el.surface1.radius)
            r2_str = fmt_len(el.surface2.radius)
            r3_str = fmt_len(el.surface3.radius)
            t1_str = fmt_len(el.thickness1)
            t2_str = fmt_len(el.thickness2)
            d_str = fmt_len(el.diameter)
            y_str = fmt_len(el.axial_position)
            
            n1_func = resolve_refractive_index(el.glass1, el.nd1, el.vd1)
            n2_func = resolve_refractive_index(el.glass2, el.nd2, el.vd2)
            n1_val = round(n1_func(primary_wvl), digits=5)
            n2_val = round(n2_func(primary_wvl), digits=5)
            
            println(buf, "# $(el.name) (Cemented: $(el.glass1) + $(el.glass2))")
            println(buf, "$var_name = SphericalDoubletLens($r1_str, $r2_str, $r3_str, $t1_str, $t2_str, $d_str, λ -> $n1_val, λ -> $n2_val)")
            println(buf, "translate3d!($var_name, [0.0, $y_str, 0.0])")
            println(buf, "")
            elem_counter += 1

        elseif isa(el, ZmxTriplet)
            var_name = "triplet_$elem_counter"
            push!(obj_names, var_name)
            
            r1_str = fmt_len(el.surface1.radius)
            r2_str = fmt_len(el.surface2.radius)
            r3_str = fmt_len(el.surface3.radius)
            r4_str = fmt_len(el.surface4.radius)
            t1_str = fmt_len(el.thickness1)
            t2_str = fmt_len(el.thickness2)
            t3_str = fmt_len(el.thickness3)
            d_str = fmt_len(el.diameter)
            y_str = fmt_len(el.axial_position)
            
            n1_val = round(resolve_refractive_index(el.glass1)(primary_wvl), digits=5)
            n2_val = round(resolve_refractive_index(el.glass2)(primary_wvl), digits=5)
            n3_val = round(resolve_refractive_index(el.glass3)(primary_wvl), digits=5)

            println(buf, "# $(el.name) (Cemented Triplet: $(el.glass1) + $(el.glass2) + $(el.glass3))")
            println(buf, "$var_name = SphericalTripletLens($r1_str, $r2_str, $r3_str, $r4_str, $t1_str, $t2_str, $t3_str, $d_str, λ -> $n1_val, λ -> $n2_val, λ -> $n3_val)")
            println(buf, "translate3d!($var_name, [0.0, $y_str, 0.0])")
            println(buf, "")
            elem_counter += 1

        elseif isa(el, ZmxMirror)
            var_name = "mirror_$elem_counter"
            push!(obj_names, var_name)
            
            d_str = fmt_len(el.diameter)
            y_str = fmt_len(el.axial_position)
            t_str = fmt_len(max(el.diameter * 0.1, 0.005))
            println(buf, "# $(el.name)")
            if isinf(el.surface.radius)
                println(buf, "$var_name = RoundPlanoMirror($d_str, $t_str)")
            else
                r_str = fmt_len(el.surface.radius)
                println(buf, "$var_name = SphericalMirror($r_str, $t_str, $d_str)")
            end
            println(buf, "translate3d!($var_name, [0.0, $y_str, 0.0])")
            println(buf, "")
            elem_counter += 1

        elseif isa(el, ZmxStop)
            y_str = fmt_len(el.axial_position)
            d_str = fmt_len(el.diameter)
            println(buf, "# Aperture Stop: position y = $y_str, clear aperture = $d_str")
            println(buf, "")

        elseif isa(el, ZmxDetector)
            det_name = "detector"
            d_str = fmt_len(el.diameter)
            y_str = fmt_len(el.axial_position)
            println(buf, "# --- Detector (Image Plane) ---")
            println(buf, "$det_name = Detector($d_str)")
            println(buf, "translate3d!($det_name, [0.0, $y_str, 0.0])")
            println(buf, "")
        end
    end

    println(buf, "# --- System Assembly ---")
    if length(obj_names) == 1
        println(buf, "optics = $(obj_names[1])")
    else
        println(buf, "optics = ObjectGroup([$(join(obj_names, ", "))])")
    end
    
    if !isempty(det_name)
        println(buf, "system = System([optics, $det_name])")
    else
        println(buf, "system = System([optics])")
    end
    println(buf, "")
    println(buf, "# --- Simulation Example ---")
    println(buf, "primary_wvl = $(primary_wvl) # [m]")
    println(buf, "source = CollimatedSource([0.0, -10.0mm, 0.0], [0.0, 1.0, 0.0], 5.0mm, primary_wvl, num_rays=500, num_rings=10)")
    println(buf, "solve_system!(system, source)")
    if !isempty(det_name)
        println(buf, "hits = spot_diagram($det_name)")
        println(buf, "println(\"Detector hits: \", length(hits))")
    end

    return String(take!(buf))
end

"""
    generate_bmo_code(filepath::AbstractString)::String

Convenience wrapper: parses a .zmx file and returns the generated Julia code string.
"""
function generate_bmo_code(filepath::AbstractString)::String
    zmx_sys = parse_zmx(filepath)
    elements = group_elements(zmx_sys)
    return generate_bmo_code(zmx_sys, elements)
end

"""
    generate_bmo_script(zmx_filepath::AbstractString, output_jl_filepath::AbstractString)

Generates and saves a standalone Julia script representing the optical system.
"""
function generate_bmo_script(zmx_filepath::AbstractString, output_jl_filepath::AbstractString)
    code = generate_bmo_code(zmx_filepath)
    write(output_jl_filepath, code)
    return output_jl_filepath
end

